### ISSUE TITLE
Restarting bot -> bot forgets polls

### ISSUE THREAD

**Issue by trigrab** [fachschaft/rocketbot#1]
When restarting the bot, older polls can not be changed anymore.

Maybe we should use a pickle.

**Comment by dekuenstle** [comment]
You might have a look at [shelve](https://docs.python.org/3/library/shelve.html) for storing the polls. 
They are automatically persisted dictionaries (via pickle).

**Comment by smoehrle** [comment]
Feature is implemented. Polls are persisted in a separat room as json. This also enables admins/users who are allowed to edit messages to modify/fix/delete polls since the bot syncs the poll and status messages
